# Generated by Django 3.2.6 on 2025-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='eeg_files/')),
                ('recording_date', models.DateTimeField(blank=True, null=True)),
                ('num_signals', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('sampling_rates', models.JSONField(default=dict)),
                ('channel_names', models.JSONField(default=list)),
            ],
        ),
    ]
