# Generated by Django 3.2.6 on 2025-03-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejadorPacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to='manejadorPacientes.paciente')),
            ],
        ),
    ]
