# Generated by Django 3.2.6 on 2025-04-02 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manejadorPacientes', '0001_initial'),
        ('manejadorEEGFile', '0001_initial'),
        ('manejadorHClinicas', '0002_alter_historialclinico_ruta_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_prueba', models.CharField(choices=[('EEG', 'pruebaEEG'), ('MRI', 'pruebaMRI'), ('MiRNA', 'pruebaMiRNA')], default='EEG', max_length=10)),
                ('fecha', models.DateTimeField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('presencia_anomalia', models.BooleanField(default=False)),
                ('tipo_anomalia', models.CharField(blank=True, max_length=255, null=True)),
                ('presencia_lesion', models.BooleanField(default=False)),
                ('tipo_lesion', models.CharField(blank=True, max_length=255, null=True)),
                ('presencia_sobreexpresion', models.BooleanField(default=False)),
                ('eeg_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manejadorEEGFile.eegfile')),
                ('historial_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejadorHClinicas.historialclinico')),
                ('paciente', models.ManyToManyField(to='manejadorPacientes.Paciente')),
            ],
        ),
    ]
