# Generated by Django 3.2.6 on 2025-03-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condiciones_medicas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
